name: mol_suite_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyside6
  - pyvista
  - pyvistaqt
  - vtk
  - pyscf
  - matplotlib
  - numpy
  - scipy
  - psutil
  - pyperclip
  - cclib
  - h5py
  - pip
  - conda-pack
